project:
  type: website
website:
  title: "A STATISTICAL MODELING GUILD"
  description: "Website containing descriptions, documentation, and demonstrations for models that the author and friends have built."
  site-url: "https://O957.github.io/Aggregated-Model-Descriptions/"
  search:
    location: navbar
    type: overlay
  navbar:
    background: gray
    right:
      - about.qmd
      - icon: github
        href: https://github.com/O957
  page-footer:
    left: "Copyright 2024, O957"
  favicon: icon.jpg
format:
  html:
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: true
